### PR TITLE
fix: localizations

### PR DESCRIPTION
**Pull request by ymauray**
# Description

A whitespace has been added to a localizable message in the code, but the .po files have not been updated.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my code in common scenarios and confirmed there are no regressions

### CODE REVIEW

**Comment by ymauray** [comment]
There is no automated process for that. And I have no clue how to put one in place.
The best course of action is to not touch the text in "context.t("Blah")", as this is the key that is used to fetch the messages in the .po files.
It might be worth investigating how to look at the code for calls to context.t 
Maybe a code generator?

**Comment by flexiondotorg** [comment]
So how did all those .po files get updated exactly?

**Comment by ymauray** [comment]
I updated them all by hand.

**Comment by ymauray** [comment]
I think in debug mode, an exception should be thrown if a message is not found in the current language file (probably english, or french). Therefore, the developper would have to add the message at least one .po file, and hopefully, think about adding it to quickgui.pot

**Comment by ymauray** [comment]
By the way, currently, when a message is not found, it is displayed in the console.

**Review by flexiondotorg — APPROVED** [review]

**Pull request merged**
